/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.question.one;

import org.junit.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.*;

public class QuestionOneTest {

    @Test
    public void testListPrimeNumbersFor30(){
        List<Integer> expectedPrimeNumberList = Arrays.asList(2, 3, 5, 7, 11, 13, 17, 19, 23, 29);

        List<Integer> actualPrimeNumberList = QuestionOne.listPrimeNumbers(30);

        assertEquals(expectedPrimeNumberList, actualPrimeNumberList);
    }

    @Test
    public void testListPrimeNumbersFor100(){

        List<Integer> expectedPrimeNumberList = Arrays.asList(2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97);

        List<Integer> actualPrimeNumberList = QuestionOne.listPrimeNumbers(100);

        assertEquals(expectedPrimeNumberList, actualPrimeNumberList);

    }
}
